### ISSUE TITLE
not  work 

### ISSUE THREAD

**Issue by mangotango69202** [dfrnoch/discord-sniper#12]
i have installed python the latest but still i get this error
![image](https://user-images.githubusercontent.com/70999479/98132807-d4689d00-1ee2-11eb-9878-0f3be54459d0.png)

![image](https://user-images.githubusercontent.com/70999479/98132859-e2b6b900-1ee2-11eb-8c33-d453a2418c0b.png)
i also did repair and still get the same error

**Comment by 0wb** [comment]
change the -3.8 on the installer to -3.9

**Comment by mangotango69202** [comment]
how

**Comment by mangotango69202** [comment]
ERROR: Failed building wheel for multidict
RROR: Could not build wheels for yarl, multidict which use PEP 517 and cannot be installed directly

**Comment by mangotango69202** [comment]
Traceback (most recent call last):
  File "C:\Users\______\Desktop\______\discord-sniper-master\Main.py", line 3, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

**Comment by 0wb** [comment]
`pip install requests`

**Comment by mangotango69202** [comment]
what?

**Comment by mangotango69202** [comment]
ok it worked now see I don't want to snipe nitro I just want it to join the giveaway and the bot they use is different and the emoji so I edited the main.py and added the bots id and also put the emoji and it doesn't join the giveaway 
edit the id bots id is 748489355894587432 and the emoji that they use is :ok_hand: /774274450513985557

**Comment by mangotango69202** [comment]
this is what i edited 
if 'GIVEAWAY' in message.content:
        if giveaway_sniper:
            if message.author.id == 748489355894587432 or message.author.id == 748489355894587432 or message.author.id == 748489355894587432 or message.author.id == 748489355894587432:
                try:
                    if not edelay:
                        await message.add_reaction("👌")
                except discord.errors.Forbidden:
                    print(""
                          f"\n{Fore.RED}{time} - Couldnt React to Giveaway" + Fore.RESET)
                    GiveawayInfo()
                if edelay:
                    print(""
                          f"\n{Fore.GREEN}{time} - Giveaway Found!" + Fore.RESET)
                    GiveawayDelayInfo()
                else:
                    print(""
                          f"\n{Fore.GREEN}{time} - Giveaway Sniped" + Fore.RESET)
                    GiveawayInfo()
                if notification:
                    if edelay:
                        toaster.show_toast("Sniper",
                                           f"Sniping Giveaway in {delay}s. Look into console",
                                           icon_path="./drop.ico",
                                           duration=7)
                    else:
                        toaster.show_toast("Sniper",
                                           "Giveaway Sniped! Look into console",
                                           icon_path="./drop.ico",
                                           duration=7)
                try:
                    if edelay:
                        sleep(delay)
                        await message.add_reaction("👌")
                        print("")
                        print(f"{Fore.GREEN}Giveaway Sniped with delay {delay} seconds!")
                except discord.errors.Forbidden:
                    print(""
                          f"\n{Fore.RED}{time} - Couldnt React to Giveaway" + Fore.RESET)
                    GiveawayInfo()
        else:
            return
    if f'Congratulations <@{Sniper.user.id}>' in message.content or f'<@{Sniper.user.id}> won' in message.content:
        if giveaway_sniper:
            if message.author.id == 748489355894587432 or message.author.id == 748489355894587432 or message.author.id == 748489355894587432 or message.author.id == 748489355894587432 or message.author.id == 748489355894587432:
                print(""
                      f"\n{Fore.GREEN}{time} - Giveaway Won" + Fore.RESET)
                GiveawayInfo()
                if notification:
                    toaster.show_toast("Sniper",
                                       "Giveaway Won! Look into console",
                                       icon_path="./drop.ico",
                                       duration=7)
