### ISSUE TITLE
can we host it on heroku

### ISSUE THREAD

**Issue by JagritThukral** [dfrnoch/discord-sniper#29]
is there to way to host it somewhere so that it works even when my pc is off. tried on heroku but it showed a a error :-

 Collecting pypiwin32
         Downloading pypiwin32-223-py3-none-any.whl (1.7 kB)
       Collecting aiohttp<3.8.0,>=3.6.0
         Downloading aiohttp-3.7.3-cp36-cp36m-manylinux2014_x86_64.whl (1.3 MB)
       ERROR: Could not find a version that satisfies the requirement pywin32>=223 (from pypiwin32->win10toast->-r /tmp/build_270d1229_/requirements.txt (line 5)) (from versions: none)
       ERROR: No matching distribution found for pywin32>=223 (from pypiwin32->win10toast->-r /tmp/build_270d1229_/requirements.txt (line 5))
 !     Push rejected, failed to compile Python app.
 !     Push failed

**Comment by lukehodges** [comment]
Change requirements.txt line 5 to pywin32

**Comment by JagritThukral** [comment]
Actually i got the issue heroku is linux based and this pywin is for windows and it helps in giving notification so i removed the notification part from the code and removed its requirement so it worked

**Comment by dfrnoch** [comment]
sometimes I will make a branch for vps in which I remove unnecessary and not supported things.
