### ISSUE TITLE
Replace discord.py with discord.py-self

### ISSUE THREAD

**Issue by MateiSR** [dfrnoch/discord-sniper#42]
Replace discord.py with discord.py-self in requirements.txt to make the selfbot work again.
https://github.com/dolfies/discord.py-self
https://stackoverflow.com/questions/67339174/discord-api-soft-ban-for-selfbot-it-can-only-read-its-own-messages

**Comment by MateiSR** [comment]
Also, remove bot=true from the Sniper.run() method

**Comment by ghost** [comment]
use the selfcord branch, you can still use discord.py for other stuff then instead of getting conflicting issues

**Comment by MohammedKamona** [comment]
![fixxx](https://user-images.githubusercontent.com/83495139/208542741-8abc8b3a-541a-4e92-98e9-ab53e7a48fb6.png)
how i can fix it??
