### ISSUE TITLE
Request: A few requests (multi-user, stats in title etc.)

### ISSUE THREAD

**Issue by rondDev** [dfrnoch/discord-sniper#5]
Hey, I have a few ideas that might improve the project as a whole, you don't have to implement them, but you could (:

- Logs (log to file, errors, redemptions etc.)
- Multiple user sniping (ability to use 2, 3 or even 17 accounts to snipe on), this feature would be a great addition because it makes it possible to snipe in virtually unlimited amount of discord servers.
- Stats in title (Sniped 2/36, meaning 36 nitros were sent, but only 2 were redeemed etc.)
- Discord Webhook

That's all I can think of off the top of my head 😄

**Comment by rondDev** [comment]
Added webhook in my pull request.

**Comment by dfrnoch** [comment]
Thanks for contributing! I've merged pull request to master branch. I've already working on multiple accounts, so in next update it may be in. And Title stats are great idea too, so I will implement that.
