### ISSUE TITLE
Don't use this on your main acc (Yet)

### ISSUE THREAD

**Issue by UltraBlackLinux** [dfrnoch/discord-sniper#8]
Due to its speed and stuff, this program puts you on high risk of getting your discord account suspended.
Unless youre on an alt, dont use this. Who knows if discord has an ip banning system so all your accounts might be at risk.
Hope this will at least be made slower.

**Comment by dfrnoch** [comment]
Hi, I wrote that using selfbot is bannable, hovever discord **does not** giving IP ban or HWID ban, just block your account. And there's very low chance of getting banned usig this program unless you got reported by someone.
